drop table product if exists;
drop table category if exists;
drop table unit if exists;

create table category (
    id integer generated by default as identity (start with 1),
    name varchar(255) not null unique,
    primary key (id)
);

create table product (
    id integer generated by default as identity (start with 1),
    description varchar(255),
    name varchar(255) not null,
    purchasePrice float(53) not null,
    quantityUnit varchar(255) not null,
    sellingPrice float(53) not null,
    category_id integer not null,
    unit_id integer not null,
    primary key (id)
);

create table unit (
    id integer generated by default as identity (start with 1),
    name varchar(255) not null unique,
    primary key (id)
);

alter table product
   add constraint FK1mtsbur82frn64de7balymq9s
   foreign key (category_id)
   references category;

alter table product
   add constraint FKndrubbm6whifirg6o2bpdcf6b
   foreign key (unit_id)
   references unit;
