
drop table product if exists;
drop table category if exists;
drop table unit if exists;

    create table category (
        id integer generated by default as identity (start with 1),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table product (
        id integer generated by default as identity (start with 1),
        description varchar(255),
        name varchar(255) not null,
        purchasePrice float(53) not null,
        quantityUnit varchar(255) not null,
        sellingPrice float(53) not null,
        category_id integer not null,
        unit_id integer not null,
        primary key (id)
    );

    create table unit (
        id integer generated by default as identity (start with 1),
        name varchar(255) not null unique,
        primary key (id)
    );

    alter table product
       add constraint FK1mtsbur82frn64de7balymq9s
       foreign key (category_id)
       references category;

    alter table product
       add constraint FKndrubbm6whifirg6o2bpdcf6b
       foreign key (unit_id)
       references unit;


INSERT INTO category (name) VALUES
('Élelmiszer'),
('Elektronika'),
('Irodaszer'),
('Tisztítószer');

INSERT INTO unit (name) VALUES
('db'),
('kg'),
('csomag'),
('liter');

INSERT INTO product (
    name, description, purchasePrice, sellingPrice, quantityUnit, category_id, unit_id
) VALUES
('Tej 1L', 'Friss 1 literes tej', 250, 350, 1, 1, 4),
('Kenyér', 'Fehér kenyér 1kg', 400, 550, 2, 1, 1),
('Laptop', '15.6 colos irodai laptop', 150000, 185000, 3, 2, 1),
('Egér', 'Vezeték nélküli optikai egér', 3000, 4500, 4, 2, 1),
('Nyomtatópapír A4', '500 lapos A4 papírcsomag', 1200, 1800, 5, 3, 3),
('Golyóstoll', 'Kék tintájú toll', 80, 150, 6, 3, 1),
('Felmosó folyadék', 'Univerzális tisztítószer 1L', 500, 900, 7, 4, 4),
('Mosogatószer', 'Citrus illatú 0.5L', 350, 650, 8, 4, 4),
('Cukor 1kg', 'Kristálycukor 1kg kiszerelés', 300, 450, 9, 1, 2),
('Notebook', 'Füzet, spirálos, 80 lap', 250, 450, 10, 3, 1);
